"""Exploratory local RAG over evidence-linked PDF passages."""

from dev.rag_mvp.rag import (
    Answer,
    CitationAudit,
    CitationAuditRow,
    CitationCandidate,
    CitationClaim,
    CitationProposal,
    IngestedDocument,
    Passage,
    SearchHit,
    answer,
    audit_citations,
    citation_proposal,
    display_page_label,
    extract_pdf,
    index_documents,
    initialize_database,
    load_bibtex_keys,
    load_citation_claims,
    search,
    search_citation_candidates,
)

__all__ = [
    "Answer",
    "CitationAudit",
    "CitationAuditRow",
    "CitationCandidate",
    "CitationClaim",
    "CitationProposal",
    "IngestedDocument",
    "Passage",
    "SearchHit",
    "answer",
    "audit_citations",
    "citation_proposal",
    "display_page_label",
    "extract_pdf",
    "index_documents",
    "initialize_database",
    "load_bibtex_keys",
    "load_citation_claims",
    "search",
    "search_citation_candidates",
]
